Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,37 +13,111 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v2
 
-    - name: Login to Docker Hub
-      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
-      # Проверьте успешность входа
-      if: success()
-
     - name: Build Docker Image
       run: |
-        docker build -t ${{ secrets.DOCKER_USERNAME }}/lenta:latest ./lenta
-      # Проверьте успешность сборки
+        docker build -t myimage:latest .
       if: success()
     
-    - name: Push Docker Container Image
+    - name: Check Docker Image
       run: |
-        docker push ${{ secrets.DOCKER_USERNAME }}/lenta:latest
-      # Проверьте успешность пуша
+        if docker images | grep -q "myimage:latest"; then
+          echo "Docker image found: myimage:latest"
+        else
+          echo "Docker image not found: myimage:latest"
+          exit 1
+        fi
+      if: success()
+
+    - name: Push Docker Image to Docker Hub
+      run: |
+        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+        docker tag myimage:latest ${{ secrets.DOCKER_USERNAME }}/myimage:latest
+        docker push ${{ secrets.DOCKER_USERNAME }}/myimage:latest
       if: success()
 
     - name: Cleanup Docker images
       run: docker image prune -f
 
-    - name: Notify on success
+    - name: Send Telegram Notification On Build Success
       if: success()
-      run: |
-        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
-        -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
-        -d "text=Сборка и публикация образа успешно завершены!"
+      uses: appleboy/telegram-action@master
+      with:
+        to: ${{ secrets.TELEGRAM_TO }}
+        token: ${{ secrets.TELEGRAM_TOKEN }}
+        message: "Сборка образа успешно завершена!"
 
-    - name: Notify on failure
+    - name: Send Telegram Notification On Build Failure
       if: failure()
-      run: |
-        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
-        -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
-        -d "text=Произошла ошибка при сборке или публикации образа."
+      uses: appleboy/telegram-action@master
+      with:
+        to: ${{ secrets.TELEGRAM_TO }}
+        token: ${{ secrets.TELEGRAM_TOKEN }}
+        message: "Произошла ошибка при сборке образа."
+
+    - name: Send Telegram Notification On Push Success
+      if: success()
+      uses: appleboy/telegram-action@master
+      with:
+        to: ${{ secrets.TELEGRAM_TO }}
+        token: ${{ secrets.TELEGRAM_TOKEN }}
+        message: "Отправка образа на Docker Hub успешно завершена!"
+
+    - name: Send Telegram Notification On Push Failure
+      if: failure()
+      uses: appleboy/telegram-action@master
+      with:
+        to: ${{ secrets.TELEGRAM_TO }}
+        token: ${{ secrets.TELEGRAM_TOKEN }}
+        message: "Произошла ошибка при отправке образа на Docker Hub."
+
+
+
+# name: Build and Push Docker Image
+
+# on:
+#   push:
+#     branches:
+#       - main
+
+# jobs:
+#   build-and-push:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#     - name: Checkout repository
+#       uses: actions/checkout@v2
+
+#     - name: Login to Docker Hub
+#       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+#       # Проверьте успешность входа
+#       if: success()
+
+#     - name: Build Docker Image
+#       run: |
+#         docker build -t ${{ secrets.DOCKER_USERNAME }}/lenta:latest ./lenta
+#       # Проверьте успешность сборки
+#       if: success()
+    
+#     - name: Push Docker Container Image
+#       run: |
+#         docker push ${{ secrets.DOCKER_USERNAME }}/lenta:latest
+#       # Проверьте успешность пуша
+#       if: success()
+
+#     - name: Cleanup Docker images
+#       run: docker image prune -f
+
+#     - name: Notify on success
+#       if: success()
+#       run: |
+#         curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
+#         -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
+#         -d "text=Сборка и публикация образа успешно завершены!"
+
+#     - name: Notify on failure
+#       if: failure()
+#       run: |
+#         curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
+#         -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
+#         -d "text=Произошла ошибка при сборке или публикации образа."
 
