Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,19 +23,44 @@ jobs:
 
     - name: Build Multi-Platform Docker Image
       run: |
-         docker buildx build \
-           --builder mybuilder \
-           -t ${{ secrets.DOCKER_USERNAME }}/lenta:latest \
-           ./lenta
-       # Проверьте успешность сборки
+        docker buildx build \
+          --builder mybuilder \
+          -t ${{ secrets.DOCKER_USERNAME }}/lenta:latest \
+          ./lenta
+      # Проверьте успешность сборки
+      if: success()
+
+    - name: Check Docker Image
+      run: |
+        if docker images | grep -q "${{ secrets.DOCKER_USERNAME }}/lenta"; then
+          echo "Docker image found: ${{ secrets.DOCKER_USERNAME }}/lenta"
+        else
+          echo "Docker image not found: ${{ secrets.DOCKER_USERNAME }}/lenta"
+          exit 1
+        fi
+      # Проверьте успешность выполнения
       if: success()
 
     - name: Push Docker Container Image
       run: |
-         docker buildx use mybuilder
-         docker buildx build \
-           --builder mybuilder \
-           -t ${{ secrets.DOCKER_USERNAME }}/lenta:latest \
-           ./lenta
-       # Проверьте успешность пуша
+        docker buildx use mybuilder
+        docker push ${{ secrets.DOCKER_USERNAME }}/lenta:latest
+      # Проверьте успешность пуша
       if: success()
+
+    - name: Cleanup Docker images
+      run: docker image prune -f
+
+    - name: Notify on success
+      if: success()
+      run: |
+        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
+        -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
+        -d "text=Сборка и публикация образа успешно завершены!"
+
+    - name: Notify on failure
+      if: failure()
+      run: |
+        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
+        -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
+        -d "text=Произошла ошибка при сборке или публикации образа."
